server:
  port: 5004
spring:
  # 配置activemq
  activemq:
    broker-url: tcp://13.114.143.193:61616
    user: admin
    password: admin
  jms:
    # 指定是类型为Topic
    pub-sub-domain: true
# 自定义队列名称
my-topic: test.boot.activemq.topic