server:
  port: 5002
spring:
  # 配置activemq
  activemq:
    broker-url: tcp://13.114.143.193:61616
    user: admin
    password: admin
# 自定义队列名称 可以事先不指定是Queue还是Topic，默认为Queue
my-queue: test.boot.activemq.queue